<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3registration"
 *
 * Auto generated by Extension Builder 2014-02-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'T3Registration',
	'description' => 'T3Registration registration users for TYPO3',
	'category' => 'plugin',
	'author' => 'Federico Bernardin',
	'author_email' => 'federico.bernardin@immaginario.com',
	'author_company' => 'BFConsulting',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '2.0',
	'constraints' => array(
		'depends' => array(
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>